### ISSUE TITLE
Batch change all records to make the data model uniform

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#103]
First make a list of which batch changes need to be made, some of which appear in earlier issues

**Comment by wlpotter** [comment]
Wait until #102 is done

**Comment by wlpotter** [comment]
## high priority

- [ ] duplicate `/editor[@role="creator"]` elements for JLR
- [ ] make taxonomy for chronology uniform (some whitespace issues too but those are low priority) (cf. #92 ). This also includes deleting the category Iron IIc (see #95 )
- [ ] all records should have a `desc[@type="context"]`
- [ ] every `ab[@type="edition"]` should have three notes of type textual, discussion, and corrigenda
- [ ] every `ab[@type="translation"]` should have three notes of type translation, discussion, and corrigenda
- [ ] all records should have 8 bibls total (2 for edition and translation and 6 for additional bibls). Cf. #94 
- [ ] all records should have four `/TEI/text/body/note` elements with `@type` values of "related-texts", "geography", "prosopography", and "themes". Each of these may have data in tei:p elements (for cleaning up of this data see #108)

## check with editors

- [ ] m-level title. Current "Caesarea Maritima: A Collection of Testimonia" (this is on the website currently)
- [ ] seriesStmt s-level title. Current "Caesarea-Maritima.org: A Digital Archive" (this is on the website as well)

## lower priority

- [ ] blank respStmt for URNs and other metadata
- [ ] whitespace inconsistencies throughout teiHeader
- [ ] blank creator editors in titleStmt
- [ ] editorialDecl (not sure if just whitespace or content changes), still need to check on

**Comment by wlpotter** [comment]
two records seem to be missing "related-texts" notes.

There appear to be duplicated "themes" notes in two records.

Need more investigation to figure out which.

**Comment by wlpotter** [comment]
All of these have been made except for normalizing the whitespace (this is always a thorny issue...maybe one day I will figure out all of Oxygen's whitespace settings but for now I will leave this until later).
